INSERT INTO `account` (`status`, `account_id`, `email`, `full_name`, `password`, `phone`) VALUES
	(1, 'cam', 'cam@gmail.com', 'Van My Cam', '123', '0249234293403'),
	(1, 'loi', 'loi@gmail.com', 'Pham Tan Loi', '123', '0985456320'),
	(1, 'met', 'met@gmail.com', 'Tran Thi Met', '123', '0904567890'),
	(1, 'phong', 'phong@gmail.com', 'Nguyen Tan Phong', '123', '0945674421'),
	(1, 'phonNguyen', 'phongNguyen1@gmail.com', 'Nguyen Tan Phong', '123', '0956532238'),
	(1, 'son', 'son@gmail.com', 'Nguyen Thanh Son', '123', '0387866829'),
	(1, 'sonPham', 'sonPham@gmail.com', 'Phạm Thanh Sơn', '123', '24234234324'),
	(1, 'teo', 'teo@gmail.com', 'Nguyen Van Teo', '123', '0903123456');
INSERT INTO `role` (`status`, `description`, `role_id`, `role_name`) VALUES
	(1, 'admin role', 'admin', 'administrator'),
	(1, 'delete from Customer table', 'deleteCustomer', 'delete Customer'),
	(1, 'delete from Employee table', 'deleteEmployee', 'delete Employee'),
	(1, 'delete from Order table', 'deleteOrder', 'delete Order'),
	(1, 'delete from Product table', 'deleteProduct', 'delete Product'),
	(1, 'insert into Customer table', 'insertCustomer', 'insert Customer'),
	(1, 'insert into Employee table', 'insertEmployee', 'insert Employee'),
	(1, 'insert into Order table', 'insertOrder', 'insert Order'),
	(1, 'insert into Product table', 'insertProduct', 'insert Product'),
	(1, 'select from Customer table', 'selectCustomer', 'select Customer'),
	(1, 'select from Employee table', 'selectEmployee', 'select Employee'),
	(1, 'select from Order table', 'selectOrder', 'select Order'),
	(1, 'select from Product table', 'selectProduct', 'select Product'),
	(1, 'update Customer table', 'updateCustomer', 'update Customer'),
	(1, 'update Employee table', 'updateEmployee', 'update Employee'),
	(1, 'update Order table', 'updateOrder', 'update Order'),
	(1, 'update Product table', 'updateProduct', 'update Product'),
	(1, 'user role - allow access', 'user', 'user');
INSERT INTO `grant_access` (`is_grant`, `account_id`, `note`, `role_id`) VALUES
	(b'1', 'cam', '', 'deleteCustomer'),
	(b'0', 'cam', '', 'deleteEmployee'),
	(b'1', 'cam', '', 'deleteProduct'),
	(b'1', 'cam', '', 'updateEmployee'),
	(b'1', 'cam', '', 'updateOrder'),
	(b'1', 'cam', '', 'user'),
	(b'1', 'loi', '', 'insertOrder'),
	(b'1', 'loi', '', 'selectEmployee'),
	(b'0', 'loi', '', 'updateOrder'),
	(b'1', 'loi', '', 'user'),
	(b'1', 'met', '', 'selectOrder'),
	(b'1', 'met', '', 'updateOrder'),
	(b'1', 'met', '', 'user'),
	(b'1', 'phonNguyen', '', 'user'),
	(b'1', 'son', '', 'admin'),
	(b'1', 'sonPham', '', 'deleteProduct'),
	(b'1', 'sonPham', '', 'user'),
	(b'1', 'teo', '', 'user');